# config.yaml

# 1) download (step1.py)
download:
  base_url:    "https://byjus.com/ncert-books"
  output_dir:  "ncert_pdfs"
  concurrency: 6

# 2) database + pdf ingestion (step2.py)
database:
  url:  "sqlite:///ncert_content.db"
  echo: false

pdf:
  base_dir:     "ncert_pdfs"
  fallback_to_pdfplumber: true

# 3) export (step3.py)
export:
  jsonl_path: "ncert_dataset.jsonl"
