version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://app:8000
    networks:
      - app-network

networks:
  app-network:
    external: true
