# docker-compose.yml
version: "3.8"

services:
  app:
    build: .
    container_name: ncert_mcq_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../airflow/dags:/airflow/dags:ro
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    pid: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    pid: host
    restart: unless-stopped
    command:
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev)($|/)"

volumes:
  postgres_data:
  prometheus_data:
